{{- if .Values.certs.grpc.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dex.fullname" . }}-openssl-config
data:
  openssl.conf: |
{{ .Files.Get "config/openssl.conf" | indent 4 }}
{{- end }}
